In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [3]:
# Load data
data = pd.read_csv('data/m16_cpu_usage_detect.csv')
data['time'] = pd.to_datetime(data['time'])
data = data.set_index('time')
data.head()

cpu_util  anomaly
time                                        
2017-11-05 02:00:00+00:00  0.279063        0
2017-11-05 02:05:00+00:00  0.274687        0
2017-11-05 02:10:00+00:00  0.293007        0
2017-11-05 02:15:00+00:00  0.290867        0
2017-11-05 02:20:00+00:00  0.288103        0

In [9]:
# Split data
split_size = int(len(data) * 0.8)
train_data = data[:split_size]
test_data = data[split_size:]

In [14]:
X = train_data['cpu_util'].values
y = train_data['anomaly'].values

X, y

(array([0.27906333, 0.27468667, 0.29300667, ..., 0.17406   , 0.17583667,
        0.17389333]),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64))

In [18]:
# Build model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(32, activation='relu', input_shape=(1,)),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

In [19]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [20]:
# Train model
model.fit(X, y, epochs=100)

Epoch 1/100


293/293 [==============================] - 1s 2ms/step - loss: 0.4482 - accuracy: 0.9627
Epoch 2/100
293/293 [==============================] - 0s 1ms/step - loss: 0.1528 - accuracy: 0.9842
Epoch 3/100
293/293 [==============================] - 0s 1ms/step - loss: 0.1030 - accuracy: 0.9842
Epoch 4/100
293/293 [==============================] - 0s 1ms/step - loss: 0.0822 - accuracy: 0.9842
Epoch 5/100
293/293 [==============================] - 0s 1ms/step - loss: 0.0639 - accuracy: 0.9842
Epoch 6/100
293/293 [==============================] - 0s 1ms/step - loss: 0.0516 - accuracy: 0.9842
Epoch 7/100
293/293 [==============================] - 0s 1ms/step - loss: 0.0454 - accuracy: 0.9842
Epoch 8/100
293/293 [==============================] - 0s 1ms/step - loss: 0.0420 - accuracy: 0.9842
Epoch 9/100
293/293 [==============================] - 0s 1ms/step - loss: 0.0401 - accuracy: 0.9842
Epoch 10/100
293/293 [==============================] - 0s 1ms/step - loss: 0.0391 - accuracy: 0.9842
E

In [21]:
# Predict
X_test = test_data['cpu_util'].values
y_test = test_data['anomaly'].values


In [22]:
def predict(x):
    return model.predict(x)

In [44]:
predict([0.2, 0.8, 0.5, 0.6, 0.7, 0.8, 0.86, 0.86, 0.86, 0.86, 0.86, 0.4, 0.5])

1/1 [==============================] - 0s 52ms/step


array([[4.8252579e-04],
       [5.1040399e-01],
       [2.1941572e-02],
       [7.4634694e-02],
       [2.2478762e-01],
       [5.1040399e-01],
       [6.9197810e-01],
       [6.9197810e-01],
       [6.9197810e-01],
       [6.9197810e-01],
       [6.9197810e-01],
       [6.2012188e-03],
       [2.1941572e-02]], dtype=float32)

In [42]:
6.9197810e-01

0.6919781